[package]
edition = "2018"
authors = [
    "The ToolsTeam <tools@teams.rust-embedded.org>",
    "Jorge Aparicio <jorge@japaric.io>",
]
build = "build.rs"
categories = [
    "command-line-utilities",
    "embedded",
    "hardware-support",
    "no-std",
]
description = "Generate Rust register maps (`struct`s) from SVD files"
documentation = "https://docs.rs/svd2rust"
keywords = [
    "svd",
    "embedded",
    "register",
    "map",
    "generator",
]
license = "MIT OR Apache-2.0"
name = "svd4rust"
repository = "https://github.com/rust-embedded/svd2rust/"
version = "0.17.0"
readme = "README.md"

[dependencies]
cast = "0.2"
clap = "2.33"
env_logger = "~0.7"
inflections = "1.1"
log = { version = "~0.4", features = ["std"] }
quote = "1.0"
proc-macro2 = "1.0"
anyhow = "1.0.19"
thiserror = "1.0.5"
regex = "1.4.3"
serde = { version = "1.0.123", features = [ "derive" ]}
serde_yaml = "0.8.15"
svd-parser = { version = "0.9", features = ["derive-from"] }
syn = { version = "1.0", features = ["full","extra-traits"] }
